comment-jira-link:
  enabled: true
delete-merged-branch:
  enabled: true
  exclude:
    - master
merge-pull-request:
  enabled: true
  label: merge this
update-jira-status:
  enabled: true
  component: jbcli
