name: Push develop

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        sleep 10
