name: Release

on:
  push:
    tags:
      - '*'

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
    - name: Step 1
      run: |
        sleep 2
        echo Done.
    - name: Step 2
      run: |
        sleep 2
        echo Done.
    - name: Step 3
      run: |
        sleep 2
        echo Done.
  job2:
    name: Job 2
    runs-on: ubuntu-latest

    steps:
    - name: Step 1
      run: |
        sleep 2
        echo Done.
    - name: Step 2
      run: |
        sleep 2
        echo Done.
    - name: Step 3
      run: |
        sleep 2
        echo Done.
  job3:
    name: Send Slack message
    runs-on: ubuntu-latest
    needs:
      - job1
      - job2

    steps:
      - name: Get tag
        run: |
          git_ref="${GITHUB_REF#refs/tags/}"
          echo "git_ref=$git_ref" >> $GITHUB_ENV
      - name: Debug git tag
        run: |
          echo "git_ref: $git_ref"
      - name: Send Slack message
        uses: archive/github-actions-slack@master
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_JITTERBOT_USER_TOKEN }}
          slack-channel: CSSJPN9TQ
          slack-text: |-
            <@UK0HRR56K> Jitterbot Testing ${{ env.git_ref }} has been built. Please deploy from Octopus.
            <https://jitterbit.atlassian.net/issues/?jql=cf%5B10700%5D%20%3D%20%22${{ env.git_ref }}%22%20AND%20component%20%3D%20%22Cloud%20Studio%22|Tickets in this release.>
            CC <@UJN4XC89Z>
