name: Release

on:
  push:
    tags:
      - '*'

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
    - name: Step 1
      run: |
        sleep 2
        echo Done.
    - name: Step 2
      run: |
        sleep 2
        echo Done.
    - name: Step 3
      run: |
        sleep 2
        echo Done.
  job2:
    name: Job 2
    runs-on: ubuntu-latest

    steps:
    - name: Step 1
      run: |
        sleep 2
        echo Done.
    - name: Step 2
      run: |
        sleep 2
        echo Done.
    - name: Step 3
      run: |
        sleep 2
        echo Done.
